# Generated by Django 5.0 on 2024-01-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
