# Generated by Django 5.0 on 2024-01-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
