# Generated by Django 5.0 on 2024-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_place_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='desc',
            field=models.TextField(),
        ),
    ]
